/*
 * Copyright (c) 2016, ARM Limited and Contributors. All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

#ifndef ROCKCHIP_SIP_SVC_H
#define ROCKCHIP_SIP_SVC_H

/* SMC function IDs for SiP Service queries */
#define SIP_SVC_CALL_COUNT		0x8200ff00
#define SIP_SVC_UID			0x8200ff01
#define SIP_SVC_VERSION			0x8200ff03
#define RK_SIP_SCMI_AGENT0		0x82000010

/* Rockchip SD/MMC Control Service (for Windows on Arm) */
#define RK_SIP_SDMMC_CLOCK_RATE_GET		0x82000020
#define RK_SIP_SDMMC_CLOCK_RATE_SET		0x82000021
#define RK_SIP_SDMMC_CLOCK_PHASE_GET		0x82000022
#define RK_SIP_SDMMC_CLOCK_PHASE_SET		0x82000023
#define RK_SIP_SDMMC_REGULATOR_VOLTAGE_GET	0x82000024
#define RK_SIP_SDMMC_REGULATOR_VOLTAGE_SET	0x82000025
#define RK_SIP_SDMMC_REGULATOR_ENABLE_GET	0x82000026
#define RK_SIP_SDMMC_REGULATOR_ENABLE_SET	0x82000027

/* rockchip SiP Service Calls version numbers */
#define RK_SIP_SVC_VERSION_MAJOR	0x1
#define RK_SIP_SVC_VERSION_MINOR	0x0

/* Number of ROCKCHIP SiP Calls implemented */
#define RK_COMMON_SIP_NUM_CALLS		0x3

/*
 * RK_SIP_SDMMC definitions
*/
typedef enum {
	RK_SIP_SDMMC_CLOCK_ID_MSHC_CIU = 0,
	RK_SIP_SDMMC_CLOCK_ID_MSHC_CIU_DRIVE,
	RK_SIP_SDMMC_CLOCK_ID_MSHC_CIU_SAMPLE
} RK_SIP_SDMMC_CLOCK_ID_MSHC;

typedef enum {
	RK_SIP_SDMMC_CLOCK_ID_EMMC_CCLK = 0
} RK_SIP_SDMMC_CLOCK_ID_EMMC;

typedef enum {
	RK_SIP_SDMMC_REGULATOR_ID_SUPPLY = 0,
	RK_SIP_SDMMC_REGULATOR_ID_SIGNAL
} RK_SIP_SDMMC_REGULATOR_ID;

enum {
	RK_SIP_E_SUCCESS = 0,
	RK_SIP_E_NOT_SUPPORTED = -1, // SMC_UNK
	RK_SIP_E_INVALID_PARAM = -2,
	RK_SIP_E_NOT_IMPLEMENTED = -3,
	RK_SIP_E_DEVICE_ERROR = -4,
};

#endif /* ROCKCHIP_SIP_SVC_H */
